spring:
  application:
    name: api-server
  profiles:
    active: local
  
  # Database Configuration
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:studyaid}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: app

  # Avoid duplication with docker-compose.yml
  flyway:
    enabled: false

  # Redis Configuration
  data:
    redis:
      host: ${REDIS_HOST:localhost:}
      port: ${REDIS_PORT:6379:}

  # servlet
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /api

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

# JWT Configuration
jwt:
  issuer: studyaid
  access-token-ttl-ms: 900000  # 15분
  refresh-token-ttl-ms: 1209600000  # 2주

storage:
  bucket: study-aid-lecture-materials
  cloudfront-endpoint: ${CLOUDFRONT_ENDPOINT:https://example-cloudfront.net}

# SQS Configuration
sqs:
  generate-summary:
    queue-url: ${SQS_GENERATE_SUMMARY_QUEUE_URL}

google:
  oauth2:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: ${GOOGLE_REDIRECT_URI:https://studyaid.academy/auth/google/callback}
    token-uri: https://oauth2.googleapis.com/token
    user-info-uri: https://www.googleapis.com/oauth2/v2/userinfo
    refresh-token-ttl-ms: 15552000000 # 6개월 (180일)