spring:
  # Database Configuration
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:studyaid}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /api

# Swagger UI Configuration
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    enabled: true

# Logging
logging:
  level:
    org.springframework: INFO
    com.example.api: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.example.api.adapters.llm.OpenAIAdapter: DEBUG

# JWT Configuration
jwt:
  secret_key: ${JWT_SECRET_KEY}

minio:
  endpoint: http://minio:9000
  access-key: minioadmin
  secret-key: minioadmin

aws:
  region: ap-northeast-2

# LocalStack Configuration
localstack:
  endpoint: http://localstack:4566

# SQS Configuration for Local Testing
sqs:
  generate-summary:
    queue-url: http://sqs.ap-northeast-2.localstack.localstack.cloud:4566/000000000000/local-study-aid-summarize-lecture

# LangChain Server
langchain:
  server:
    url: http://langchain-server:5000

# WebClient, RestTemplate Configuration
web-client:
  connect-timeout-ms: 3000 # 3s
  response-timeout-ms: 60000 # 60s
  max-in-memory-size: 10485760 # 10MB

rest-template:
  connect-timeout-ms: 3000 # 3s
  read-timeout-ms: 60000 # 60s