version: '3.8'

services:
  postgres-test:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: studyaid
    ports:
      - "5433:5432"
    volumes:
      - postgres-test-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  localstack-test:
    image: localstack/localstack:2.0.0
    environment:
      SERVICES: s3
      DEBUG: 1
      LOCALSTACK_VOLUME_DIR: /opt/localstack/data
      PERSISTENCE: 1
    ports:
      - "4567:4566"
    volumes:
      - localstack-test-data:/opt/localstack/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4566/_localstack/health" ]
      interval: 5s
      timeout: 5s
      retries: 5

  # 초기 S3 버킷 생성
  setup-s3:
    image: amazon/aws-cli:2.9.1
    depends_on:
      localstack-test:
        condition: service_healthy
    environment:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_DEFAULT_REGION: ap-northeast-2
    entrypoint: >
      /bin/sh -c "
        aws --endpoint-url=http://localstack-test:4566 s3 mb s3://study-aid-materials || true;
        echo 'S3 bucket created.';
        exit 0;
      "

  # 테스트 데이터베이스 설정
  setup-db:
    build:
      context: ../../
      dockerfile: jobs/test_env/Dockerfile.test
    depends_on:
      postgres-test:
        condition: service_healthy
    environment:
      DB_HOST: postgres-test
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: studyaid
      AWS_ENDPOINT_URL: http://localstack-test:4566
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_REGION: ap-northeast-2
      S3_BUCKET: study-aid-materials
      OPENAI_API_KEY: ${OPENAI_API_KEY:-test_key}
      OPENAI_MODEL: ${OPENAI_MODEL:-gpt-4o}
    volumes:
      - ../../:/app
    command: [ "python", "/app/jobs/test_env/setup_test_db.py" ]

  # 디버깅용 셸 환경
  shell:
    build:
      context: ../../
      dockerfile: jobs/test_env/Dockerfile.test
    depends_on:
      - postgres-test
      - localstack-test
    environment:
      DB_HOST: postgres-test
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: studyaid
      AWS_ENDPOINT_URL: http://localstack-test:4566
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_REGION: ap-northeast-2
      S3_BUCKET: study-aid-materials
      OPENAI_API_KEY: ${OPENAI_API_KEY:-test_key}
      OPENAI_MODEL: ${OPENAI_MODEL:-gpt-4o}
    volumes:
      - ../../:/app
    working_dir: /app
    entrypoint: [ "/bin/bash" ]
    profiles:
      - shell

  # 요약 기능 테스트 (summarize_lecture)
  test-summarize:
    build:
      context: ../../
      dockerfile: jobs/test_env/Dockerfile.test
    depends_on:
      - postgres-test
      - localstack-test
      - setup-s3
      - setup-db
    environment:
      DB_HOST: postgres-test
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: studyaid
      AWS_ENDPOINT_URL: http://localstack-test:4566
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_REGION: ap-northeast-2
      S3_BUCKET: study-aid-materials
      OPENAI_API_KEY: ${OPENAI_API_KEY:-test_key}
      OPENAI_MODEL: ${OPENAI_MODEL:-gpt-4o}
      DEFAULT_CHUNK_SIZE: 3
    volumes:
      - ../../:/app
    command: [ "python", "/app/jobs/test_env/run_test_job.py", "--job", "summarize_lecture" ]
    profiles:
      - summarize

  # 퀴즈 생성 기능 테스트 (generate_quiz)
  test-quiz:
    build:
      context: ../../
      dockerfile: jobs/test_env/Dockerfile.test
    depends_on:
      - postgres-test
      - localstack-test
      - setup-s3
      - setup-db
    environment:
      DB_HOST: postgres-test
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: studyaid
      AWS_ENDPOINT_URL: http://localstack-test:4566
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_REGION: ap-northeast-2
      S3_BUCKET: study-aid-materials
      OPENAI_API_KEY: ${OPENAI_API_KEY:-test_key}
      OPENAI_MODEL: ${OPENAI_MODEL:-gpt-4o}
    volumes:
      - ../../:/app
    command: [ "python", "/app/jobs/test_env/run_test_job.py", "--job", "generate_quiz" ]
    profiles:
      - quiz

  # 시험 생성 기능 테스트 (generate_exam)
  test-exam:
    build:
      context: ../../
      dockerfile: jobs/test_env/Dockerfile.test
    depends_on:
      - postgres-test
      - localstack-test
      - setup-s3
      - setup-db
    environment:
      DB_HOST: postgres-test
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: studyaid
      AWS_ENDPOINT_URL: http://localstack-test:4566
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_REGION: ap-northeast-2
      S3_BUCKET: study-aid-materials
      OPENAI_API_KEY: ${OPENAI_API_KEY:-test_key}
      OPENAI_MODEL: ${OPENAI_MODEL:-gpt-4o}
    volumes:
      - ../../:/app
    command: [ "python", "/app/jobs/test_env/run_test_job.py", "--job", "generate_exam" ]
    profiles:
      - exam

  # 퀴즈 서술형 채점 기능 테스트 (grade_quiz_essay)
  test-grade-quiz-essay:
    build:
      context: ../../
      dockerfile: jobs/test_env/Dockerfile.test
    depends_on:
      - postgres-test
      - localstack-test
      - setup-db
    environment:
      DB_HOST: postgres-test
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: studyaid
      AWS_ENDPOINT_URL: http://localstack-test:4566
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_REGION: ap-northeast-2
      OPENAI_API_KEY: ${OPENAI_API_KEY:-test_key}
      OPENAI_MODEL: ${OPENAI_MODEL:-gpt-4o}
      PROMPT_VERSION: latest
    volumes:
      - ../../:/app
    command: [ "python", "/app/jobs/test_env/run_test_job.py", "--job", "grade_quiz_essay" ]
    profiles:
      - grade-quiz-essay

  # 시험 서술형 채점 기능 테스트 (grade_exam_essay)
  test-grade-exam-essay:
    build:
      context: ../../
      dockerfile: jobs/test_env/Dockerfile.test
    depends_on:
      - postgres-test
      - localstack-test
      - setup-db
    environment:
      DB_HOST: postgres-test
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: studyaid
      AWS_ENDPOINT_URL: http://localstack-test:4566
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_REGION: ap-northeast-2
      OPENAI_API_KEY: ${OPENAI_API_KEY:-test_key}
      OPENAI_MODEL: ${OPENAI_MODEL:-gpt-4o}
      PROMPT_VERSION: latest
    volumes:
      - ../../:/app
    command: [ "python", "/app/jobs/test_env/run_test_job.py", "--job", "grade_exam_essay" ]
    profiles:
      - grade-exam-essay

  # 과목 약점 분석 및 학습 제안 레포트 생성 기능 테스트 (generate_course_weakness_analysis)
  test-generate-course-weakness-analysis:
    build:
      context: ../../
      dockerfile: jobs/test_env/Dockerfile.test
    depends_on:
      - postgres-test
      - localstack-test
      - setup-db
    environment:
      DB_HOST: postgres-test
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: studyaid
      AWS_ENDPOINT_URL: http://localstack-test:4566
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_REGION: ap-northeast-2
      OPENAI_API_KEY: ${OPENAI_API_KEY:-test_key}
      OPENAI_MODEL: ${OPENAI_MODEL:-gpt-4o}
      PROMPT_VERSION: latest
    volumes:
      - ../../:/app
    command: [ "python", "/app/jobs/test_env/run_test_job.py", "--job", "generate_course_weakness_analysis" ]
    profiles:
      - generate-course-weakness-analysis


volumes:
  postgres-test-data:
  localstack-test-data:
